<?php
/**
 * Created by PhpStorm.
 * User: higo
 * Date: 04/10/16
 * Time: 02:01
 */

namespace Tests;

use App\Mapper\Projeto;

class ProjetoTest extends BaseUnitTests
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Projeto $projeto
     * @test
     * @dataProvider dataFactory
     */
    public function testNameProjeto(Projeto $projeto) {
        $this->assertTrue($projeto->getNome() == "Predio");
    }

    public function dataFactory() {
        $projeto = new Projeto();
        $projeto->setNome('Predio');

        return [
            [$projeto]
        ];
    }

}